name: sync-images

on:
  push:
    branches:
      - master
  # schedule:
  #   - cron: "* */6 * * *"

jobs:
  sync-images:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          path: tools

      - name: Checkout official-images repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.TOKEN_GITHUB }}
          fetch-depth: 0
          repository: ${{ github.repository_owner }}/official-images
          path: official-images

      - name: Config git user and user.email
        run: |
          cd ${GITHUB_WORKSPACE}/official-images && git config user.name github-actions
          cd ${GITHUB_WORKSPACE}/official-images && git config user.email github-actions@github.com

      - name: Set up skopeo environment
        uses: warjiang/setup-skopeo@v0.1.3

      - name: Sync images to registry
        shell: bash
        env:
          REGISTRY_DOMAIN: ${{ secrets.REGISTRY_DOMAIN }}
          REGISTRY_USER: ${{ secrets.REGISTRY_USER }}
          REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
          REGISTRY_HOSTS: ${{ secrets.REGISTRY_HOSTS }}
        run: |
          # echo 'deb http://download.opensuse.org/repositories/home:/alvistack/xUbuntu_22.04/ /' | sudo tee /etc/apt/sources.list.d/home:alvistack.list
          # curl -fsSL https://download.opensuse.org/repositories/home:alvistack/xUbuntu_22.04/Release.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/home_alvistack.gpg > /dev/null
          # sudo apt update && sudo apt install skopeo
          skopeo --version
          # podman run docker://quay.io/skopeo/stable:latest --help
          echo ${REGISTRY_HOSTS} | sudo tee -a /etc/hosts
          sudo skopeo login ${REGISTRY_DOMAIN} -u ${REGISTRY_USER} -p ${REGISTRY_PASSWORD} --tls-verify=false
          sudo bash ${GITHUB_WORKSPACE}/tools/sync.sh ${REGISTRY_DOMAIN} ${GITHUB_WORKSPACE}/official-images
      # for debug action runner
      #- name: Setup tmate session
      #  uses: mxschmitt/action-tmate@v1
